GET  http://localhost:4000/

###

POST http://localhost:4000/admin
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET  http://localhost:4000/allusers

###

POST http://localhost:4000/adduser
Content-Type: application/json

{
    "name": "sistatest",
    "password": "sistatest",
    "subscribed": false
}

###

POST http://localhost:4000/subscribe
Content-Type: application/json

{
    "id": "UJJtzB_q142TnSiWDLFLI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "kalleanka",
    "password": "kalleanka"
}

###
POST http://localhost:4000/blogs
Content-Type: application/json

{
    "title": "nytt igen",
    "text": "nytt igen",
    "author": "gKgkRScUC0obiAwzm0zhm"
}

###
DELETE  http://localhost:4000/deleteuser/gKgkRScUC0obiAwzm0zhm

###
GET http://localhost:4000/blogs/b24_dlDk_6wyHC-9qHhXl
###
DELETE http://localhost:4000/blogs/qFjNbBatTAsO7Rb2zPVRs