GET  http://localhost:4000

###

POST http://localhost:4000/adduser
Content-Type: application/json

{
    "name": "kalle",
    "password": "anka"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "kalle",
    "password": "anka"
}

###
POST http://localhost:4000/blogs
Content-Type: application/json

{
    "title": "nytt test",
    "text": "test text",
    "author": "Og_dp5EuS1kVH3EuXnFTj"
}

###
GET http://localhost:4000/blogs/ZbqmjsOzte56I5PQc6BBf

###
DELETE http://localhost:4000/blogs/QVTDbGe_rNVH4xovxcYYS